services:
  memento-mcp-server:
    build: .
    ports:
      - "9001:9001"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/memory.db
      - LOG_LEVEL=info
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=9001
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    user: root
    command: ["/app/start-container.sh"]
    stdin_open: true
    tty: true

  # Redis for caching (optional)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes

volumes:
  redis_data:
