name: Build and Deploy

on:
  push:
    branches: [ '*' ]  # 모든 브랜치 지원
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Check if dist folder exists
      run: |
        if [ -d "dist" ]; then
          echo "dist folder exists"
          ls -la dist/
        else
          echo "dist folder does not exist"
          exit 1
        fi
    
    - name: Commit dist folder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 충돌 방지: main 브랜치와 병합
        git fetch origin main
        git merge origin/main --strategy-option=theirs || true
        
        # dist 폴더 강제 추가 및 커밋
        git add -f dist/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: build dist folder [skip ci]"
          git push origin ${{ github.ref_name }}
        fi
